### ISSUE TITLE
When the disk name contains "space" it will fail

### ISSUE THREAD

**Issue by luyong6** [edwin-wang/usb_remount#1]
For example, my disk name is "My Data" 
And the script cannot handle this space character.

**Comment by edwin-wang** [comment]
Known issue reported by Huaxin before.

**Comment by edwin-wang** [comment]
@luyong6 Could you please verify it. I added new regexp to handle volume identifier with space.

**Comment by luyong6** [comment]
> On branch idf_w_space
Your branch is up to date with 'origin/idf_w_space'.

```
sudo ./usb_remount
df: option requires an argument -- T
usage: df [-b | -H | -h | -k | -m | -g | -P] [-ailn] [-T type] [-t] [filesystem ...]
Volume NO NAME on disk3s1 unmounted
usage: mount [-dfruvw] [-o options] [-t external_type] special node
       mount [-adfruvw] [-t external_type]
       mount [-dfruvw] special | node
re-mount error: mount -t  /dev/disk3s1 /Volumes/NO NAME
return: 1
```

**Comment by edwin-wang** [comment]
It was caused by my coreutils version "df" - Apple's inbox df has a different definition... Let me get more ideas...

**Comment by edwin-wang** [comment]
@luyong6 Use "mount" instead of "df -T". Could you verify it again?
